"use client";

import React, { useState } from "react";
import {
  AlertTriangle,
  Flame,
  Scissors,
  Wrench,
  CheckCircle2,
  Send,
  Zap,
  Clock,
} from "lucide-react";
import { formatNaira } from "@/lib/utils";

export const ToolingSentinelAlert: React.FC = () => {
  const [poDispatched, setPoDispatched] = useState<boolean>(false);

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 rounded-xl bg-amber-500/20 border border-amber-500/40 flex items-center justify-center text-amber-400">
            <Wrench className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white flex items-center space-x-2">
              <span>Predictive Tooling & Consumables Sentinel</span>
              <span className="px-2 py-0.5 rounded bg-amber-950 text-amber-300 border border-amber-800 text-[10px] font-mono">
                Hardware Health AI
              </span>
            </h3>
            <p className="text-xs text-slate-400">
              Tracks blade cut cycles, glue pot thermal curves, and edge tape roll stocks to trigger preventive maintenance before factory downtime.
            </p>
          </div>
        </div>

        <span className="text-xs font-mono text-amber-400 bg-amber-950/80 px-3 py-1.5 rounded-xl border border-amber-800 flex items-center space-x-1.5">
          <AlertTriangle className="w-3.5 h-3.5" />
          <span>1 Proactive Maintenance Recommendation</span>
        </span>
      </div>

      {/* Alert Card */}
      <div className="bg-gradient-to-r from-amber-950/40 via-slate-950 to-slate-950 border border-amber-500/40 rounded-2xl p-6 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center font-black">
              <Scissors className="w-5 h-5" />
            </div>
            <div>
              <div className="text-sm font-bold text-white">
                Sliding Panel Saw SCMI Si400 — Main Scoring Blade Sharpening Due
              </div>
              <div className="text-xs text-slate-400">
                Current Blade Cuts: <strong className="text-amber-400 font-mono">428 / 500 max cuts</strong>. Micro-chipping risk on High Gloss Acrylic boards expected in ~72 cuts.
              </div>
            </div>
          </div>

          <span className="px-2.5 py-1 rounded bg-amber-900/60 text-amber-300 text-xs font-bold font-mono">
            Preventive Threshold Reached
          </span>
        </div>

        {/* Action Generated by Sentinel */}
        <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="text-xs space-y-1">
            <div className="font-bold text-white">
              Autonomous Purchase Order Generated: #PO-2026-TOOL-88
            </div>
            <div className="text-slate-400">
              Vendor: <strong>Lagos Precision Tooling & Blade Sharpeners (Mushin / Matori)</strong> | 2x Replacement Freud Carbide Blades on Standby
            </div>
          </div>

          {poDispatched ? (
            <div className="flex items-center space-x-1.5 text-xs text-emerald-400 font-bold bg-emerald-950 px-3 py-2 rounded-xl border border-emerald-800">
              <CheckCircle2 className="w-4 h-4" />
              <span>Sharpening Pickup Booked for 6:00 PM</span>
            </div>
          ) : (
            <button
              onClick={() => setPoDispatched(true)}
              className="px-4 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs shadow-lg shadow-amber-500/20 flex items-center space-x-1.5 transition-all flex-shrink-0"
            >
              <Send className="w-3.5 h-3.5" />
              <span>Approve Blade Service & Auto-Dispatch Vendor</span>
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
